export let acron_to_phrase = {
    ATI:	    "Acentuação da trama intersticial",
    AMD:	    "Alargamento mediastinal",
    ACCTCT:	    "A critério clínico complementar com TC de tórax, para melhor avaliação.",
    ACCTCAP:	"A critério clínico complementar com “TC” de abdome e pelve.",
    AIOSMGPA:	"A idade óssea segundo o método de Greulich-Pyle é de aproximadamente",
    ARA:	    "A radiografia de abdome não avalia de forma acurada, ou pode não mostrar determinadas lesões,  assim como pequenos cálculos, portanto recomendamos complementar com “TC” de abdome e pelve, para melhor avaliação.",
    ARC:	    "A radiografia de crânio não avalia de forma acurada, ou pode não mostrar determinadas lesões, portanto recomendamos complementar com “TC” de crânio, para melhor avaliação.",
    ACD:	    "Acentuação da cifose dorsal",
    ATBVB:	    "Acentuação da trama broncovascular, bilateral",
    ATIB:	    "Acentuação da trama intersticial bilateral",
    ATVZHPH:	"Acentuação da trama vascular nas zonas hilares e para-hilares",
    ACLC:	    "Acromioclavicular",
    ADJ:	    "Adjacente",
    ACFPTL:	    "Afundamento central focal no platô tibial lateral",
    ACFPTM:	    "Afundamento central focal no platô tibial medial",
    ATDPTL:	    "Afundamento total com deslocamento do platô tibial lateral",
    ATDPTM:	    "Afundamento total com deslocamento do platô tibial medial",
    AGSF:	    "Agenesia do seio fontal",
    ASFS:	    "Agenesia dos seios fontais", 
    AHI:	    "Alargamento Hilar",
    AMP:	    "Alargamento mediastinal paratraqueal",
    AOMP:	    "Alguns osteófitos marginais periarticulares",
    AAT:	    "Alongamento da aorta torácica",
    AM:	        "Ambas as mãos",
    AH:	        "Ambos Hemitóraces",
    AJ:	        "Ambos os joelhos",
    AO:	        "Ambos os ombros",
    AP:	        "Ambos os pés",
    ACP:	    "Análise cardíaca prejudicada",
    AAPA:	    "Aorta alongada com placa de ateroma calcificada na croça",
    AAA:	    "Aorta alongada e ateromatosa",
    AA:	        "Aorta anatômica",
    AUPD:	    "Apófises unciformes proeminentes de",
    ACLMN:	    "Área cardíaca nos limites máximos da normalidade",
    ADS: 	    "Articulada a direita ao sacro",
    AES:	    "Articulada a esquerda ao sacro",
    ABSSOS:	    "Articulada bilateralmente ao sacro , com sinais de osteoartrite secundária",
    AS: 	    "Articuladas ao sacro",
    APLA:	    "Artrose dos processos interapofisários",
    ACOMP:	    "Aspecto compatível",
    AEDDC:	    "Atitude escoliótica dorsal dextro convexa",
    AEDSC:	    "Atitude escoliótica dorsal sinistro convexa",
    AELDC:	    "Atitude escoliótica lombar dextro convexa",
    AELSC:	    "Atitude escoliótica lombar sinistro convexa",
    AAC:	    "Aumento da área cardíaca",
    AACSIC:	    "Aumento da área cardíaca segundo o índice cardiotorácico",
    APMA:	    "Aumento das partes moles adjacentes",
    APM:	    "Aumento de partes moles",
    AALSF:	    "Aumento do ângulo lombo sacro de Ferguson.",
    AVC:	    "Aumento do volume cardíaco",
    AGVC:	    "Aumento global do volume cardíaco",
    AHBPNV: 	"Aumento hilar bilateral provavelmente de natureza vascular",
    ALPA:	    "Ausência de lesão parenquimatosa em atividade",
    ASF:	    "Ausência de sinais de fratura",
    ASLPA:	    "Ausência de sinais de lesão pleuro pulmonar em atividade",
    B:	        "Bilateral",
    BPS:	    "Broncopneumônicas",
    BCA:	    "Buracos de conjugação de amplitude de aspecto normal",
    CCC:	    "Calcificações condrocostais",
    CLIP:	    "Calcificação ligamentar infrapatelar",
    CLSIP:	    "Calcificação ligamentar supra e infrapatelar", 
    CLSP:	    "Calcificação ligamentar suprapatelar",
    CAS:	    "Calcificações ateromatosas",
    CAA:	    "Calcificações ateromatosas na aorta abdominal",
    CAAT:	    "Calcificações ateromatosas na aorta torácica",
    CACA:	    "Calcificações ateromatosas na croça da aorta",
    CAF:	    "Calcificações de anéis fibrosos",
    CPAAF:	    "Calcificações parietais ateromatosas na artéria femoral",
    CPAAFS:	    "Calcificações parietais ateromatosas nas artérias femorais",
    CV:	        "Calcificações vasculares",
    CE:	        "Células etmoidais",
    CEA:    	"Células etmoidais anteriores",
    COA:    	"Centro de ossificação acessório",
    CD:	        "Cifoescoliose dorsal",
    CSOS:   	"Com sinais de osteoartrite secundária",
    CFLS:   	"Côndilo femorais laterais",
    CFMS:   	"Côndilo femorais mediais",
    CFL:	    "Côndilo femoral lateral",
    CFM:	    "Côndilo femoral medial",
    CTMs:	    "Côndilo tibiais mediais",
    CTL:	    "Côndilo tibial lateral",
    CTM:	    "Côndilo tibial medial",
    CL:	        "Côndilos laterais",
    CM:	        "Côndilos mediais",
    CTLS:	    "Côndilos tibiais laterais" ,
    CI:	        "Condrocalcinose intra-articular" ,
    CVH:	    "Configuração em valgo dos hálux",
    CP:	        "Consolidação pneumônica",
    CF:     	"Controle de fratura" ,
    COC:    	"Corpos osteocondrais",
    DAFA:   	"De aspecto fibro atelectásica",
    DAFR:	    "De aspecto fibro retrátil",
    DAFC:	    "De aspecto fibrocicatricial",
    DSAP:	    "Defeito de soldadura do arco posterior",
    DPAFR:  	"Densificação parenquimatosa de aspecto fibro retrátil",
    DERP:	    "Derrame pleural",
    DSN:	    "Desvio de septo nasal",
    DSNP:	    "Desvio do septo nasal para",
    DF:	        "Diferença",
    D:	        "Direito",
    DHP:	    "Discreta hiperinsuflação pulmonar",
    DHCNI:	    "Discreta hipertrofia do corneto nasal inferior",
    DHCNIS:	    "Discreta hipertrofia dos cornetos nasais inferiores",
    DREDPE:	    "Discreta redução do espaço discal posterior entre",
    DREAIS:	    "Discreta redução dos espaços articulares das interfalangianas",
    DREAFTMP:	"Discreta redução dos espaços articulares femorotibial medial e femoropatelar",
    DREDPES:	"Discreta redução dos espaços discais posteriores entre",
    DC:	        "Discreto(a)",
    DAPM:	    "Discreto aumento das partes moles",
    DAPMA: 	    "Discreto aumento das partes moles adjacentes",
    DT:	        "Distal",
    DPD:	    "Do pulmão direito",
    DPE:	    "Do pulmão esquerdo",
    EMSM:	    "Edema de mucosa dos seios maxilares",
    EPM:	    "ELD",
    EOM:	    "Eixo ósseo mantido",
    EI:	        "Entesófitos nos ílios",
    EF:	        "Epicôndilo femoral",
    EAR:    	"Centro de ossificação acessório",
    ECC:    	"Esboço de costela cervical",
    EOSC:   	"Esclerose do osso sub-condral",
    ECS:    	"Esclerose e cistos subcondrais",
    EPVC:   	"Esclerose nos platôs vertebrais contíguos",
    EDD:    	"Escoliose dorsal direita",
    EDDPE:  	"Escoliose dorsal direita na posição do exame",
    EDE:    	"Escoliose dorsal esquerda",
    EDEPE:  	"Escoliose dorsal esquerda na posição do exame",
    EDLD:   	"Escoliose dorso lombar direita",
    EDLE:   	"Escoliose dorso lombar esquerda",
    ELD:    	"Escoliose lombar direita",
    ELDPE:  	"Escoliose lombar direita na posição do exame",
    ELE:	    "Escoliose lombar esquerda",
    ELEPE:	    "Escoliose lombar esquerda na posição do exame",
    EM:	        "Espessamento mucoso",
    EML:    	"Espessamento mucoso laminar",
    EA:	        "Espondilartrose",
    ELISE:	    "Espondilólise",
    ESTE:	    "Espondilolistese",
    E:	        "Esquerdo",
    ESD:	    "Estrias densas",
    FP:	        "Femoropatelar",
    FT:	        "Femorotibial",
    FCA:	    "Formação cálcica",
    FCAD:	    "Formação cálcica adjacente",
    FCADS:	    "Formação cálcicas adjacentes",
    FHFPLC:	    "Formação hipertrófica na face plantar do calcâneo",
    FHFPLCS: 	"Formação hipertrófica na face plantar dos calcâneos",
    FHFPPC: 	"Formação hipertrófica nas faces plantar e posterior do calcâneo",
    FHFPOC:	    "Formação hipertrófica na face posterior do calcâneo",
    FHFPOCS:	"Formação hipertrófica na face posterior dos calcâneos",
    FHFPPCS:	"Formação hipertrófica nas faces plantar e posterior dos calcâneos",
    FADPTL:	    "Fratura antiga com deslocamento no platô tibial lateral",
    FADPTM:	    "Fratura antiga com deslocamento no platô tibial medial ",
    FDPTL:	    "Fratura com deslocamento no platô tibial lateral",
    FDPTM:	    "Fratura com deslocamento no platô tibial medial",
    FCS:	    "Fratura consolidada",
    FPTL:	    "Fratura no platô tibial lateral",
    FPTM: 	    "Fratura no platô tibial medial",
    GU:	        "Glenoumeral",
    HV:	        "Hálux Valgo",
    HP:	        "Hiperinsuflação pulmonar",
    HCNI:	    "Hipertrofia do corneto nasal inferior",
    HCNIS:	    "Hipertrofia dos cornetos nasais inferiores",
    IDE:	    "Ilíaco direito mais elevado que o esquerdo",
    IED:	    "Ilíaco esquerdo mais elevado que o direito",
    II:	        "Infiltrado Intersticial",
    IN:	        "Ilíacos nivelados",
    IHN:	    "Imagem de hipotransparência nodular" ,
    IHNMSMD:	"Imagem de hipotransparência nodular medindo no seu maior diâmetro",
    INC:	    "Incipiente",
    IS:	        "Incipientes",
    ISQ:	    "Ísquios",
    L:	        "Lateral",
    LDCD:	    "Lesão degenerativa da coluna dorsal ",
    LDCL:	    "Lesão degenerativa da coluna lombar" ,
    LPCRVPB:	"Linha do PSOAS e contorno renal visibilizados parcialmente, bilateral.",
    LI:	        "Lobo inferior",
    LM:	        "Lobo médio",
    LS:	        "Lobo superior",
    MED:    	"Medial",
    MT:	        "Megapófise transversa",
    MTBL5:	    "Megapófise transversa bilateral de L5",
    MID:	    "Membro inferior direito",
    MIE:    	"Membro inferior esquerdo",
    MMD:    	"Meteorismo moderado difuso",
    NPD:    	"Na projeção do",
    NHP:    	"Não há patologia espontaneamente demonstrável pela radiografia simples de abdome.",
    NTD:    	"No terço distal",
    NTI:    	"No terço inferior",
    NTM:    	"No terço médio",
    NTP:	    "No terço proximal",
    NTS:	    "No terço superior",
    OBL:	    "Obliteração",
    OE:	        "Obliteração do etmoide",
    OSCF:	    "Obliteração do sei costo frênico",
    OHAP:	    "Opacidade heterogênea de aspecto pneumônico",
    ONA:	    "Osso navicular acessório",
    OM:	        "Osteófito marginal",
    OMA:	    "Osteófito marginal anterior",
    OMP:	    "Osteófito marginal periarticular",
    ONCV:	    "Osteófito nos corpos vertebrais",
    OI:	        "Osteófitos incipientes",
    OMS:	    "Osteófitos marginais",
    OMAS:	    "Osteófitos marginais anteriores",
    OMAPD:	    "Osteófitos marginais anteriores à partir de",
    OMACV:	    "Osteófitos marginais em alguns corpos vertebrais",
    OMPS:	    "Osteófitos marginais periarticulares",
    OF:	        "Osteofitose",
    O:	        "Osteopenia",
    OMD:	    "Osteopenia moderada",
    OOT:	    "Osteopenia nos ossos do tórax",
    OPPM:	    "Osteossíntese com placa e parafusos metálicos",
    PQ:	        "Paquipleuris",
    PC:	        "Paracardíaco",
    PHI:	    "Parahilar",
    PMA:	    "Partes moles adjacentes",
    PI:	        "Pedículos íntegros",
    PAEELI:	    "Perda do alinhamento estrutural das espinhas lombares inferiores",
    PPD:	    "Pinçamento pleuro diafragmático",
    PP:	        "Pinçamentos posteriores",
    PD:	        "Pododáctilo",
    PO:	        "Pontes ósseas",
    PAG:	    "Presença de aparelho gessado",
    PAF:	    "Projétil de arma de fogo",
    PR:	        "Proximal",
    PH:	        "Pulmões hiperinsuflados",
    PPE:	    "Pulmões pouco expandidos",
    QR:	        "Quirodáctilo",
    RA:	        "Redução da altura",
    RT:	        "Redução da transparência",
    RAEAS:	    "Redução de alguns espaços articulares",
    REA:	    "Redução do espaço articular",
    REAFT:	    "Redução do espaço articular femorotibial",
    RED:	    "Redução do espaço discal",
    REDE:	    "Redução do espaço discal entre",
    REDPE:	    "Redução do espaço discal posterior entre",
    REAFMAJ:	"Redução dos espaço articular femorotibial medial de ambos os joelhos",
    REAFMJOM:	"Redução dos espaço articular femorotibial medial de ambos os joelhos com osteófitos marginais periarticulares",
    REAS:	    "Redução dos espaços articulares",
    REAIS:	    "Redução dos espaços articulares das interfalangianas",
    REAAIS:	    "Redução dos espaços articulares de algumas interfalangianas",
    REDS:	    "Redução dos espaços discais",
    REDPD:	    "Redução dos espaços discais a partir de",
    REDES:	    "Redução dos espaços discais entre",
    REDPPD:	    "Redução dos espaços discais posteriores a partir de",
    REDPES:	    "Redução dos espaços discais posteriores entre",
    RMTBVB:	    "Reforço moderado da trama broncovascular, bilateral",
    RAAN:	    "relações articulares de aspecto normal",
    RLFL:	    "Retificação da lordose fisiológica lombar",
    REC:	    "Retificação do eixo cervical", 
    SC:	        "Seio costofrênico",
    SF:	        "Seio frontal",
    SFS:	    "Seio frontais",
    SFDT:	    "Seio frontal direito transparente",
    SFET:	    "Seio frontal esquerdo transparente",
    SM:	        "Seio maxilar",
    SCPA:	    "Seios costofrênicos pouco agudos",
    SFND:	    "Seios frontais não desenvolvidos",
    SMS:	    "Seis maxilares",
    SAA:	    "Sem alteração apreciável",
    SSP:	    "Sem significado patológico",
    SCAN:	    "Silhueta cardiotímica de aspecto normal",
    SED:	    "Sinais de espondiloartrose dorsal",
    SHA:	    "Sinais de hiperostose anquilosante",
    SHAED:	    "Sinais de hiperostose anquilosante e espondiloartrose dorsal" ,
    SOIC:	    "Sinais de osteoartrite interapofisária correspondente",
    SOIUC:	    "Sinais de osteoartrite interapofisária e uncovertebral correspondentes",
    SOILI:	    "Sinais de osteoartrite interapofisária lombar inferior",
    SOUC:	    "Sinais de osteoartrite uncovertebral correspondentes",
    SIN:	    "Sinusopatia",
    SEAP:	    "Superfícies e espaços articulares preservados",
    T:	        "Transparente",
    TC:         "TC",
    TZM:	    "Trapezometacárpico",
    TRM:	    "Trocanter maior",
    TRMS:	    "Trocanteres maiores",
    VTLS:	    "Vértebra de transição lombo sacra",
    VEL:        "Velamento",

    // TORAX (PA) - PRESET LINES
    TPA1:       "Transparência pulmonar normal",
    TPA2:       "Diâmetro transverso cardíaco preservado",
    TPA3:       "Seios costofrênicos livres",
    TPA4:       "Arcabouço ósseo normal",

    // TORAX (PA/PERFIL) - PRESET LINES
    TPP1:       "Transparência pulmonar normal",
    TPP2:       "Alongamento da aorta torácica",
    TPP3:       "Coração de configuração e diâmetros anatômicos",
    TPP4:       "Seios costofrênicos livres",
    TPP5:       "Hemicúpulas diafragmáticas convexas",
    TPP6:       "Osteopenia nos ossos do tórax",
    TPP7:       "Calcificações condrocostais",
    TPP8:       "Acentuação da cifose dorsal com oteófitos marginais em alguns corpos vertebrais",

    // SEIOS DA FACE - PRESET LINES
    SEI1:       "Seios frontais transparentes",
    SEI2:       "Células etmoidais permeáveis",
    SEI3:       "Seios maxilares sem alterações",
    SEI4:       "Seios esfenoidais de aspecto normal",
    SEI5:       "Estrutura óssea integra",
    SEI6:       "Septo nasal centrado",
    SEI7:       "Cornetos nasais de aspecto anatômicos",

    // CAVUM - PRESET LINES
    ADN1:       "Boa amplitude da coluna aérea da rinofaringe",  
    ADN2:       "Vegetações adenóides sem alterações",    
    ADN3:       "Aumento fisiológico das vegetações adenóides, mantendo-se boa a amplitude da coluna aérea da rinofaringe",    
    ADN4:       "Hipertrofia das vegetações adenóides determinando redução da amplitude da coluna aérea da rinofaringe",    
    ADN5:       "Aumento de partes moles da parede póstero superior da rinofaringe",    
    ADN6:       "Redução da amplitude da coluna aérea da rinofaringe",    

    // COLUNA CERVICAL - PRESET LINES
    CLC1:       "Corpos vertebrais de configuração anatômica",
    CLC2:       "Espaços discais conservados",
    CLC3:       "Pedículos e articulações interapofiosárias sem alterações",

    // COLUNA DORSAL - PRESET LINES
    CLD1:      "Corpos vertebrais de configuração anatômica",
    CLD2:      "Espaços invertebrais conservados",
    CLD3:      "Pedículos íntegros",

    // COLUNA LOMBAR - PRESET LINES
    CLL1:       "Corpos vertebrais de configuração anatômica",
    CLL2:       "Espaços intervertebrais conservados",
    CLL3:       "Lâminas, pedículos e articulações interapofiosárias sem alterações",
    CLL4:       "Sacro e articulações sacro-ilíacas de aspecto normal",
    CLL5:       "Fixo ósseo mantido",

    // ABDOME - PRESET LINES
    ABD1:       "Rins de topografia normal",
    ABD2:       "Meteorismo intestinal de distribuição anatômica",
    ABD3:       "Psoas-iliaco bem delineados bilateralmente",
    ABD4:       "Ausência de calcificações patológicas",
    ABD5:       "Gordura pré-peritoneal conservada",
    ABD6:       "Ausência de níveis hidroaéreos",

    // CRÂNIO - PRESET LINES
    CRN1:       "Calota craniana de espessura e estrutura normais",
    CRN2:       "Base sem alterações",
    CRN3:       "Ausência de calcificações patológicas ou de sinais de hipertensão intracraniana",
    CRN4:       "Sela turca de forma, volume e contorno ósseos normais",

    // BACIA - PRESET LINES
    BAC1:       "Estrutura óssea normal",
    BAC2:       "Sacro e articulações sacro-ilíacas de aspecto normal",
    BAC3:       "Articulações coxo-femorais sem alterações",

    // OSSOS E ARTICULAÇÕES (GERAL) - PRESET LINES
    GER1:       "Estrutura óssea normal",
    GER2:       "Partes moles sem alterações",
    GER3:       "Superfícies articulares conservadas",
    GER4:       "Espaço articular mantido",
    GER5:       "Osso sub-condral de densidade preservada",
    GER6:       "Superfícies e espaços articulares preservados",


    // VÉRTEBRAS
    C1:         "C1",
    C2:         "C2",
    C3:         "C3",
    C4:         "C4",
    C5:         "C5",
    C6:         "C6",
    C7:         "C7",

    Th1:        "Th1",
    Th2:        "Th2",
    Th3:        "Th3",
    Th4:        "Th4",
    Th5:        "Th5",
    Th6:        "Th6",
    Th7:        "Th7",
    Th8:        "Th8",
    Th9:        "Th9",
    Th10:       "Th10",
    Th11:       "Th11",
    Th12:       "Th12",
    
    L1:         "L1",
    L2:         "L2",
    L3:         "L3",
    L4:         "L4",
    L5:         "L5",

    S1:         "S1",
    S2:         "S2"
}